<<<<<<< HEAD
# Generated by Django 5.2.9 on 2026-01-05 17:18
=======
# Generated by Django 5.2.9 on 2026-01-05 21:52
>>>>>>> feature/from-archive

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
<<<<<<< HEAD
=======
from django.conf import settings
>>>>>>> feature/from-archive
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('catalog', '0002_alter_category_slug'),
=======
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> feature/from-archive
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Итого')),
                ('tg_status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки')], default='pending', max_length=16, verbose_name='Статус отправки в Telegram')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='Попыток отправки')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка')),
                ('last_error_short', models.CharField(blank=True, max_length=255, verbose_name='Последняя ошибка (кратко)')),
<<<<<<< HEAD
=======
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
>>>>>>> feature/from-archive
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название (на момент заявки)')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Цена (на момент заявки)')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявки',
                'ordering': ['id'],
            },
        ),
    ]
