CREATE TABLE "django_migrations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "app" varchar(255),
  "name" varchar(255),
  "applied" datetime
);

CREATE TABLE "django_content_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "app_label" varchar(100),
  "model" varchar(100)
);

CREATE TABLE "auth_group" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) UNIQUE
);

CREATE TABLE "auth_permission" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content_type_id" integer,
  "codename" varchar(100),
  "name" varchar(255)
);

CREATE TABLE "auth_group_permissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" integer,
  "permission_id" integer
);

CREATE TABLE "customers_customer" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "password" varchar(128),
  "last_login" datetime,
  "is_superuser" bool,
  "username" varchar(150) UNIQUE,
  "first_name" varchar(150),
  "last_name" varchar(150),
  "email" varchar(254),
  "is_staff" bool,
  "is_active" bool,
  "date_joined" datetime,
  "phone" varchar(20),
  "company" varchar(100)
);

CREATE TABLE "customers_customer_groups" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" bigint,
  "group_id" integer
);

CREATE TABLE "customers_customer_user_permissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" bigint,
  "permission_id" integer
);

CREATE TABLE "django_admin_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "object_id" text,
  "object_repr" varchar(200),
  "action_flag" smallint,
  "change_message" text,
  "content_type_id" integer,
  "user_id" bigint,
  "action_time" datetime
);

CREATE TABLE "catalog_category" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(120) UNIQUE,
  "slug" varchar(140) UNIQUE
);

CREATE TABLE "catalog_product" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(200),
  "slug" varchar(220) UNIQUE,
  "description" text,
  "size" varchar(2),
  "container_type" varchar(20),
  "condition" varchar(10),
  "is_for_sale" bool,
  "is_for_rent" bool,
  "price_sale" decimal,
  "rent_terms" varchar(200),
  "availability" varchar(20),
  "created_at" datetime
);

CREATE TABLE "catalog_product_categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint,
  "category_id" bigint
);

CREATE TABLE "catalog_productimage" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "image" varchar(100),
  "sort_order" integer,
  "product_id" bigint
);

CREATE TABLE "orders_order" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" datetime,
  "name" varchar(120),
  "phone" varchar(32),
  "email" varchar(254),
  "comment" text,
  "total" decimal,
  "tg_status" varchar(16),
  "attempts_count" integer,
  "last_attempt_at" datetime,
  "last_error_short" varchar(255),
  "customer_id" bigint
);

CREATE TABLE "orders_orderitem" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(200),
  "price" decimal,
  "qty" integer,
  "line_total" decimal,
  "order_id" bigint,
  "product_id" bigint
);

CREATE TABLE "django_session" (
  "session_key" varchar(40) PRIMARY KEY,
  "session_data" text,
  "expire_date" datetime
);

ALTER TABLE "auth_permission" ADD FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id");

ALTER TABLE "auth_group_permissions" ADD FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id");

ALTER TABLE "auth_group_permissions" ADD FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id");

ALTER TABLE "customers_customer_groups" ADD FOREIGN KEY ("customer_id") REFERENCES "customers_customer" ("id");

ALTER TABLE "customers_customer_groups" ADD FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id");

ALTER TABLE "customers_customer_user_permissions" ADD FOREIGN KEY ("customer_id") REFERENCES "customers_customer" ("id");

ALTER TABLE "customers_customer_user_permissions" ADD FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id");

ALTER TABLE "django_admin_log" ADD FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id");

ALTER TABLE "django_admin_log" ADD FOREIGN KEY ("user_id") REFERENCES "customers_customer" ("id");

ALTER TABLE "catalog_product_categories" ADD FOREIGN KEY ("product_id") REFERENCES "catalog_product" ("id");

ALTER TABLE "catalog_product_categories" ADD FOREIGN KEY ("category_id") REFERENCES "catalog_category" ("id");

ALTER TABLE "catalog_productimage" ADD FOREIGN KEY ("product_id") REFERENCES "catalog_product" ("id");

ALTER TABLE "orders_order" ADD FOREIGN KEY ("customer_id") REFERENCES "customers_customer" ("id");

ALTER TABLE "orders_orderitem" ADD FOREIGN KEY ("order_id") REFERENCES "orders_order" ("id");

ALTER TABLE "orders_orderitem" ADD FOREIGN KEY ("product_id") REFERENCES "catalog_product" ("id");
