# Generated by Django 5.2.9 on 2025-12-24 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(blank=True, choices=[('20', '20 футов'), ('40', '40 футов')], max_length=2)),
                ('container_type', models.CharField(blank=True, choices=[('standard', 'Standard'), ('high_cube', 'High-Cube')], max_length=20)),
                ('condition', models.CharField(blank=True, choices=[('new', 'Новый'), ('used', 'Б/у')], max_length=10)),
                ('is_for_sale', models.BooleanField(default=True)),
                ('is_for_rent', models.BooleanField(default=False)),
                ('price_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rent_terms', models.CharField(blank=True, max_length=200)),
                ('availability', models.CharField(choices=[('in_stock', 'В наличии'), ('on_order', 'Под заказ'), ('out', 'Нет')], default='in_stock', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
